CREATE TABLE TopicsArchived (
  ID INT UNSIGNED NOT NULL,
  Name VARCHAR(1024) NOT NULL,
  ForumId INT UNSIGNED NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID_UNIQUE (ID),
  INDEX ForumId_Index (ForumId)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;
